	$('.owl-carousel').owlCarousel({
	 	loop:true,
	    margin:5,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:false
	        },
	        600:{
	            items:1,
	            nav:false
	        },
	        50:{
	            items:1,
	            nav:false,
	            loop:true
	        }
	    }
	})